### ISSUE TITLE
Create a review model

### ISSUE THREAD

**Issue by janczizikow** [janczizikow/bnb#15]
Create a review model + add correct validations to it.
<img width="921" alt="screen shot 2018-08-13 at 2 01 55 pm" src="https://user-images.githubusercontent.com/13835666/44042119-c2f8808e-9f1f-11e8-9928-0afc220b76e9.png">

**Comment by malcolmbyu** [comment]
No pr today. Suggestion (after convo with Jan): omit Review table, and replace with columns (guest_review, guest_rating, guest_review_created_at--same for owner) inside Bookings.

**Comment by janczizikow** [comment]
fixed in #20
